CREATE TABLE IF NOT EXISTS tlab_user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended', 'withdrawn')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT REFERENCES tlab_user_account (id),
    update_by BIGINT REFERENCES tlab_user_account (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

COMMENT ON TABLE tlab_user_account IS '서비스 사용자 계정';
COMMENT ON COLUMN tlab_user_account.id IS '사용자 계정 ID';
COMMENT ON COLUMN tlab_user_account.name IS '사용자 이름';
COMMENT ON COLUMN tlab_user_account.email IS '사용자 대표 이메일 주소';
COMMENT ON COLUMN tlab_user_account.status IS '계정 상태: active, suspended, withdrawn';
COMMENT ON COLUMN tlab_user_account.created_at IS '계정 생성 시각';
COMMENT ON COLUMN tlab_user_account.updated_at IS '계정 마지막 수정 시각';
COMMENT ON COLUMN tlab_user_account.create_by IS '계정을 생성한 사용자 계정 ID';
COMMENT ON COLUMN tlab_user_account.update_by IS '계정을 마지막으로 수정한 사용자 계정 ID';
