CREATE TABLE IF NOT EXISTS tlab_user_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES tlab_user_account (id),
    provider VARCHAR(50) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(320),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,
    CONSTRAINT user_identity_provider_subject_key UNIQUE (provider, provider_subject),
    CONSTRAINT user_identity_id_provider_key UNIQUE (id, provider)
);

CREATE TABLE IF NOT EXISTS tlab_user_credential (
    user_identity_id BIGINT PRIMARY KEY,
    provider VARCHAR(50) NOT NULL DEFAULT 'local' CHECK (provider = 'local'),
    password_hash VARCHAR(255) NOT NULL,
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_credential_identity_provider_fkey
        FOREIGN KEY (user_identity_id, provider)
        REFERENCES tlab_user_identity (id, provider)
);

COMMENT ON TABLE tlab_user_identity IS '사용자의 로그인 수단';
COMMENT ON COLUMN tlab_user_identity.user_account_id IS '로그인 수단의 소유 사용자 계정 ID';
COMMENT ON COLUMN tlab_user_identity.provider IS '인증 제공자: local, google, kakao, naver 등';
COMMENT ON COLUMN tlab_user_identity.provider_subject IS '인증 제공자가 발급한 사용자의 고유 식별자';
COMMENT ON COLUMN tlab_user_identity.provider_email IS '인증 제공자가 전달한 이메일 주소';
COMMENT ON COLUMN tlab_user_identity.last_login_at IS '해당 로그인 수단의 마지막 로그인 시각';

COMMENT ON TABLE tlab_user_credential IS '로컬 로그인 수단의 비밀번호 자격 증명';
COMMENT ON COLUMN tlab_user_credential.user_identity_id IS 'local 인증 제공자를 사용하는 사용자 identity ID';
COMMENT ON COLUMN tlab_user_credential.password_hash IS '해시된 비밀번호';
COMMENT ON COLUMN tlab_user_credential.password_changed_at IS '비밀번호를 마지막으로 변경한 시각';
