CREATE TABLE IF NOT EXISTS tlab_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS tlab_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS tlab_role_permission (
    role_id BIGINT NOT NULL REFERENCES tlab_role (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES tlab_permission (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS tlab_user_role (
    user_account_id BIGINT NOT NULL REFERENCES tlab_user_account (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES tlab_role (id) ON DELETE CASCADE,
    PRIMARY KEY (user_account_id, role_id)
);

COMMENT ON TABLE tlab_role IS 'Roles assigned to user accounts';
COMMENT ON COLUMN tlab_role.id IS 'Role ID';
COMMENT ON COLUMN tlab_role.code IS 'Stable role code';
COMMENT ON COLUMN tlab_role.description IS 'Role description';

COMMENT ON TABLE tlab_permission IS 'Permissions granted to roles';
COMMENT ON COLUMN tlab_permission.id IS 'Permission ID';
COMMENT ON COLUMN tlab_permission.code IS 'Stable permission code';
COMMENT ON COLUMN tlab_permission.description IS 'Permission description';

COMMENT ON TABLE tlab_role_permission IS 'Permissions assigned to roles';
COMMENT ON COLUMN tlab_role_permission.role_id IS 'Role ID';
COMMENT ON COLUMN tlab_role_permission.permission_id IS 'Permission ID';

COMMENT ON TABLE tlab_user_role IS 'Roles assigned to user accounts';
COMMENT ON COLUMN tlab_user_role.user_account_id IS 'User account ID';
COMMENT ON COLUMN tlab_user_role.role_id IS 'Role ID';

INSERT INTO tlab_role (code, description)
VALUES
    ('admin', '관리자')
    , ('sales', '영업')
ON CONFLICT (code) DO NOTHING;

INSERT INTO tlab_permission (code, description)
VALUES
    ('user:manage', '사용자 관리')
    , ('file:manage', '파일 관리')
ON CONFLICT (code) DO NOTHING;

INSERT INTO tlab_role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM tlab_role AS role
JOIN tlab_permission AS permission
    ON permission.code in ('user:manage', 'file:manage')
WHERE role.code = 'admin'
-- UNION ALL
-- SELECT role.id, permission.id
-- FROM tlab_role AS role
-- JOIN tlab_permission AS permission
--     ON permission.code in ('file:read')
-- WHERE role.code = 'sales'
ON CONFLICT DO NOTHING;
