tracing:
  console:
    filter: info
    buffered_lines_limit: 100
    lossy: true
    ansi: false
  # file:
  #   directory: logs
  #   filename: tlab.log
  #   filter: warn
  #   buffered_lines_limit: 200
  #   lossy: false

http:
  host: "0.0.0.0"
  port: 13000
  # static_files:
  #   directory: "static"
  #   mount_path: "/static"

tls_certificate_files:
  cert: "tls-cert.pem"
  key: "tls-key.pem"
  generate_if_missing: true

database:
  url: "postgres://tlab:tlab@localhost:25432/tlab"
  max_connections: '16'

password_hash:
  memory_cost_kib: 19456
  time_cost: 2
  parallelism: 1
  output_len: 32

jwt:
  key_files:
    private_key: "jwt-private.pem"
    public_key: "jwt-public.pem"
    generate_if_missing: true
  issuer: "tlab-boilerplate"
  audience: "tlab-boilerplate"
  access_token_ttl_seconds: 900
  refresh_token_ttl_seconds: 2592000
