[package]
name = "tlab"
version = "0.1.0"
edition = "2024"

[features]
default = ["sqlxdb", "oraclersdb", "oracledb", "cachedb"]
cachedb = ["dep:deadpool-redis"]
sqlxdb = ["dep:futures-core", "dep:sqlx"]
oraclersdb = ["dep:deadpool-oracle", "dep:oracle-rs"]
oracledb = ["dep:oracledb"]

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
axum-server = { version = "0.8.0", features = ["tls-rustls-no-provider"] }
config = "0.15.25"
deadpool-oracle = { version = "0.1.1", optional = true }
deadpool-redis = { version = "0.23.0", optional = true }
futures-core = { version = "0.3.34", optional = true }
oracle-rs = { version = "0.1.7", optional = true }
oracledb = { version = "26.0.0-beta.2", optional = true }
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", optional = true, features = [
    "postgres",
    "runtime-tokio",
    "uuid",
    "chrono",
    "json",
    "sqlite",
    "mysql",
] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }

[dev-dependencies]
