/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPermissionsRouteImport } from './routes/_app.permissions'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppRolesIndexRouteImport } from './routes/_app.roles.index'
import { Route as AppRolesRoleIdPermissionsRouteImport } from './routes/_app.roles.$roleId.permissions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRolesRoute,
} as any)
const AppRolesRoleIdPermissionsRoute =
  AppRolesRoleIdPermissionsRouteImport.update({
    id: '/$roleId/permissions',
    path: '/$roleId/permissions',
    getParentRoute: () => AppRolesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/permissions': typeof AppPermissionsRoute
  '/roles': typeof AppRolesRouteWithChildren
  '/users': typeof AppUsersRoute
  '/roles/': typeof AppRolesIndexRoute
  '/roles/$roleId/permissions': typeof AppRolesRoleIdPermissionsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/permissions': typeof AppPermissionsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/roles/$roleId/permissions': typeof AppRolesRoleIdPermissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/roles': typeof AppRolesRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/roles/$roleId/permissions': typeof AppRolesRoleIdPermissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/permissions'
    | '/roles'
    | '/users'
    | '/roles/'
    | '/roles/$roleId/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/permissions'
    | '/users'
    | '/'
    | '/roles'
    | '/roles/$roleId/permissions'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/permissions'
    | '/_app/roles'
    | '/_app/users'
    | '/_app/'
    | '/_app/roles/'
    | '/_app/roles/$roleId/permissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRolesRoute
    }
    '/_app/roles/$roleId/permissions': {
      id: '/_app/roles/$roleId/permissions'
      path: '/$roleId/permissions'
      fullPath: '/roles/$roleId/permissions'
      preLoaderRoute: typeof AppRolesRoleIdPermissionsRouteImport
      parentRoute: typeof AppRolesRoute
    }
  }
}

interface AppRolesRouteChildren {
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppRolesRoleIdPermissionsRoute: typeof AppRolesRoleIdPermissionsRoute
}

const AppRolesRouteChildren: AppRolesRouteChildren = {
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppRolesRoleIdPermissionsRoute: AppRolesRoleIdPermissionsRoute,
}

const AppRolesRouteWithChildren = AppRolesRoute._addFileChildren(
  AppRolesRouteChildren,
)

interface AppRouteChildren {
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppRolesRoute: typeof AppRolesRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPermissionsRoute: AppPermissionsRoute,
  AppRolesRoute: AppRolesRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
